@baseUrl = http://localhost:8080

### Cadastrar Aluno
POST {{baseUrl}}/alunos
Content-Type: application/json

{
"nome": "João Silva",
  "dataNascimento": "2000-05-15",
  "sexo":"M",
  "telefone": "487776545",
  "celular": "489999329",
  "email": "joao@email.com",
  "observacao": "Aluno iniciante",
  "endereco": "Rua do Sol",
  "numero": 123,
  "complemento": "Apartamento 293",
  "bairro": "Centro",
  "cidade": "Ribeirão Pires",
  "estado": "SP",
  "cep": "8843910"


}


### Listar Alunos
GET {{baseUrl}}/alunos

### Listar alunos com paginação
GET {{baseUrl}}/alunos?page=0&size=10&sort=nome,asc

### Buscar aluno por ID
GET {{baseUrl}}/alunos/1

### Atualizar aluno
PUT {{baseUrl}}/alunos/1
Content-Type: application/json

{
"nome": "João Silva Atualizado",
  "dataNascimento": "2000-05-15",
  "sexo":"M",
  "telefone": "487776545",
  "celular": "489999329",
  "email": "joao@email.com",
  "observacao": "Aluno iniciante",
  "endereco": "Rua do Sol",
  "numero": 123,
  "complemento": "Apartamento 293",
  "bairro": "Centro",
  "cidade": "Ribeirão Pires",
  "estado": "SP",
  "cep": "8843910"
}


### Excluir aluno
DELETE {{baseUrl}}/alunos/1


### Cadastrar Aluno
POST {{baseUrl}}/alunos
Content-Type: application/json

{
"nome": "Maria Oliveira",
  "dataNascimento": "2001-09-26",
  "sexo":"M",
  "telefone": "487776545",
  "celular": "489999329",
  "email": "joao@email.com",
  "observacao": "Aluno iniciante",
  "endereco": "Rua do Sol",
  "numero": 123,
  "complemento": "Apartamento 293",
  "bairro": "Centro",
  "cidade": "Ribeirão Pires",
  "estado": "SP",
  "cep": "8843910"
}


### Cadastrar aluno inválido
POST {{baseUrl}}/alunos
Content-Type: application/json

{
"nome": "",
  "dataNascimento": "2001-09-26",
  "sexo":"Masculino",
  "email": "email-inválido",
  "observacao": "Aluno iniciante",
  "estado": "São Paulo",
  "cep": "8843910"
}
